# Generated by Django 2.2.4 on 2019-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('opinion', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=120)),
                ('descriptions', models.CharField(max_length=120)),
                ('url', models.URLField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogoClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=120)),
                ('descriptions', models.CharField(max_length=120)),
                ('url', models.URLField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=60, null=True)),
                ('row', models.CharField(choices=[('1', 'Row 1'), ('2', 'Row 2'), ('3', 'Row 3')], default='1', max_length=1, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='header',
            options={},
        ),
        migrations.RemoveField(
            model_name='header',
            name='image',
        ),
        migrations.RemoveField(
            model_name='header',
            name='url',
        ),
        migrations.AddField(
            model_name='header',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='subtitle',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
