# Generated by Django 2.2.4 on 2019-08-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date_finish',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='date_init',
            field=models.DateField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='page',
            name='event_type',
            field=models.CharField(choices=[('EVENTO', 'event'), ('OBRA', 'theater')], default='EVENTO', max_length=100, null=True, verbose_name='Tipo de Evento'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
