# Generated by Django 2.2.4 on 2019-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190831_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
