# Generated by Django 2.2.4 on 2019-08-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190831_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date_finish',
            field=models.DateField(null=True, verbose_name='Termino Evento'),
        ),
        migrations.AlterField(
            model_name='page',
            name='date_init',
            field=models.DateField(null=True, verbose_name='Inicio Evento'),
        ),
        migrations.AlterField(
            model_name='page',
            name='event_type',
            field=models.CharField(choices=[('event', 'EVENTO'), ('theater', 'OBRA')], default='EVENTO', max_length=100, null=True, verbose_name='Tipo de Evento'),
        ),
    ]
