# Generated by Django 2.2.4 on 2019-08-25 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_footer', to='footer.Footer')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('mdi mdi-facebook', 'Facebook'), ('mdi mdi-twitter', 'Twitter'), ('mdi mdi-google-plus', 'Google+'), ('mdi mdi-instagram', 'Instagram'), ('mdi mdi-youtube-play', 'Youtube')], default='mdi mdi-facebook', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks_footer', to='footer.Footer')),
            ],
            managers=[
                ('filter_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=14)),
                ('ubication', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('footer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_footer', to='footer.Footer')),
            ],
            managers=[
                ('filter_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('footer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='footer.Footer')),
            ],
            managers=[
                ('filter_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ButtonSubmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_submenu', to='footer.SubMenu')),
            ],
            managers=[
                ('button_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
